### ISSUE TITLE
Adding a Layer image not working on Mac OS 10.12.3

### ISSUE THREAD

**Issue by dangeratio** [McAJBen/DungeonBoard#2]
1. Opening the jar
2. Selecting the screen
3. Click Layer/Image/Paint/Loading
4. Click open file
5. Not allowing me to select any images including the PNG view3.png in the repository.

**Comment by McAJBen** [comment]
Are you currently using version 2.0.2? https://github.com/McAJBen/DungeonBoard/blob/master/Versions/Dungeon%20Board%20v2.0.2.jar

If you click the folder icon you are selecting a folder with image in it

Initially when you open the Jar it will create a folder next to it called "DungeonBoard" and its sub-folders. Try placing images inside of that and see it it works.

**Comment by dangeratio** [comment]
That version is working for me, thank you!
