### ISSUE TITLE
Lists are not alphabetized

### ISSUE THREAD

**Issue by godver3** [McAJBen/DungeonBoard#7]
I don't know if this is a bug or not but in version 2.4 the lists/files are not alphabetized. For example https://i.imgur.com/AfnOMuE.png in the Image view the files are haphazardly arranged. Similarly in the Paint menu there doesn't seem to be any sensible organization to the list https://i.imgur.com/dcEYIX7.png. Thanks.

**Comment by McAJBen** [comment]
If you could send me your image files, I cannot recreate this on my own machine. What system are you running on?

**Comment by McAJBen** [comment]
Please see if v2.4.1 fixes this issue

**Comment by godver3** [comment]
That fixed it! To answer your question I am on Windows 10 and the files
(including Dungeon Board) are all being stored at a network location.
Liam
